sudo: required
language: ruby
rvm:
  - 2.7.0
services:
  - xvfb
addons:
  chrome: stable
 
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - gem install bundler -v 2.1.4
before_script:
  - "export DISPLAY=:99.0"
